server:
  port: 8080
  servlet:
    context-path: /garden-iot
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/gardeniot
    username: root
    password: root
    driverClassName: org.postgresql.Driver


logging:
  level:
    ROOT: INFO